blank_issues_enabled: false
contact_links:
  - name: ðŸ‘¾ Chat
    url: https://discord.gg/uST2e5y4XA
    about: |
      Come join the #vite channel in the storybook discord.
  - name: ðŸ’¬ Discussion & Support
    url: https://github.com/storybookjs/builder-vite/discussions
    about: Ask a question, or share an idea.
